const number = [
    "0,cero",
    "1,uno",
    "2,dos",
    "3,tres",
    "4,cuatro",
    "5,cinco",
    "6,seis",
    "7,siete",
    "8,ocho",
    "9,nueve",
    "10,diez",
    "11,once",
    "12,doce",
    "13,trece",
    "14,catorce",
    "15,quince",
    "16,dieciseis",
    "17,diecisiete",
    "18,dieciocho",
    "19,diecinueve",
    "20,veinte",
    "21,veintiuno",
    "22,veintidos",
    "23,veintitres",
    "24,veinticuatro",
    "25,veinticinco",
    "26,veintiseis",
    "27,veintisiete",
    "28,veintiocho",
    "29,veintinueve",
    "30,treinta",
    "31,treinta y uno",
    "32,treinta y dos",
    "33,treinta y tres",
    "34,treinta y cuatro",
    "35,treinta y cinco",
    "36,treinta y seis",
    "37,treinta y siete",
    "38,treinta y ocho",
    "39,treinta y nueve",
    "40,cuarenta",
    "41,cuarenta y uno",
    "42,cuarenta y dos",
    "43,cuarenta y tres",
    "44,cuarenta y cuatro",
    "45,cuarenta y cinco",
    "46,cuarenta y seis",
    "47,cuarenta y siete",
    "48,cuarenta y ocho",
    "49,cuarenta y nueve",
    "50,cincuenta",
    "51,cincuenta y uno",
    "52,cincuenta y dos",
    "53,cincuenta y tres",
    "54,cincuenta y cuatro",
    "55,cincuenta y cinco",
    "56,cincuenta y seis",
    "57,cincuenta y siete",
    "58,cincuenta y ocho",
    "59,cincuenta y nueve",
    "60,sesenta",
    "61,sesenta y uno",
    "62,sesenta y dos",
    "63,sesenta y tres",
    "64,sesenta y cuatro",
    "65,sesenta y cinco",
    "66,sesenta y seis",
    "67,sesenta y siete",
    "68,sesenta y ocho",
    "69,sesenta y nueve",
    "70,setenta",
    "71,setenta y uno",
    "72,setenta y dos",
    "73,setenta y tres",
    "74,setenta y cuatro",
    "75,setenta y cinco",
    "76,setenta y seis",
    "77,setenta y siete",
    "78,setenta y ocho",
    "79,setenta y nueve",
    "80,ochenta",
    "81,ochenta y uno",
    "82,ochenta y dos",
    "83,ochenta y tres",
    "84,ochenta y cuatro",
    "85,ochenta y cinco",
    "86,ochenta y seis",
    "87,ochenta y siete",
    "88,ochenta y ocho",
    "89,ochenta y nueve",
    "90,noventa",
    "91,noventa y uno",
    "92,noventa y dos",
    "93,noventa y tres",
    "94,noventa y cuatro",
    "95,noventa y cinco",
    "96,noventa y seis",
    "97,noventa y siete",
    "98,noventa y ocho",
    "99,noventa y nueve",
    "10,diez",
    "20,veinte",
    "30,treinta",
    "40,cuarenta",
    "50,cincuenta",
    "60,sesenta",
    "70,setenta",
    "80,ochenta",
    "90,noventa",
    "100,ciento",
];

const mathematical = [
    "cinco + nueve,catorce",
    "uno + uno,dos",
    "cinco + tres,ocho",
    "dieciseis - siete,nueve",
    "veintiocho - veintiuno,siete",
    "once + nueve,veinte",
    "veinte + siete,veintisiete",
    "veinte - diez,diez",
    "diecinueve + tres,veintidos",
    "veintinueve - trece,dieciseis",
    "tres + nueve,doce",
    "doce + siete,diecinueve",
    "diez + veinte,treinta",
    "treinta - diez,veinte",
    "veinte + veinte,cuarenta",
    "cuarenta - diez,treinta",
    "dieciocho + veinte,treinta y ocho",
    "cuarenta - nueve,treinta y uno",
    "treinta + sesenta,noventa",
    "noventa - cincuenta,cuarenta",
    "treinta + setenta,ciento",
]

const verb = [
    "walk,caminar",
    "eat,comer",
    "drink,beber",
    "study,estudiar",
    "read,leer",
    "write,escribir",
    "feel,sentir",
    "watch,mirar",
    "work,trabajar",
    "ask,preguntar",
    "learn,aprender",
    "remember,recordar",
    "allow/permit,permitir",
    "think,pensar",
    "open,abrir",
    "sleep,dormir",
    "see,ver",
    "hungry,hambre",
    "travel,viajar"
]

const conjunction = [
    "because,poque",
    "however,sin embargo",
    "before,antes",
    "after,despues",
    "then,entonces",
    "but,pero",
    "for,para",
    "and,y",
    "or,o",
    "when,cuando",
    "if,si",
    "i have dog and cat,tengo perro y gato"
]

const question = [
    "How are you?,como estas",
    "What is your name?,como te llamas",
    "Whats your doing?,que haces",
    "Are you?,tienes",
    "Why?,por que",
    "Where?,donde",
    "Where are you?,donde estas",
    "What music do you like?,que musica te gusta",
    "What music do you like?,quien",
    "What is he?,quien es el",
    "Who do you like?,quien te gusta",
    "How,como",
    "When,quando"
]

const preposition = [
    "in/on/at,en",
    "of/from/about,de",
    "to/at clock,a",
    "with,con",
    "on/about,sobre",
    "i live at sleman,yo vivo en sleman",
    "my water in the bathroom,mi agua en el bano"
]

const thing = [
    "people,gente",
    "book,libro",
    "pencil,lapiz",
    "table,mesa",
    "father,padre",
]

const adverb = [
    "now,ahora",
    "today,hoy",
    "last night,anoche",
]

const pasttense = [
    "they ate pizza,ellos comieron pizza",
    "we traveled to bali,nosotros viajamos a bali",
    "she wrote a book,ella escribio una libro",
    "she studied,ella estudio",
    "they played,ellos jugaron",
    "you studied,tu estudiaste"
]

const konjugasipresent = [
    "yo - ar,o",
    "tu - ar,as",
    "el/ella/usted - ar,a",
    "nosotros/nosotras - ar,amos",
    "vosotros/vosotras - ar,ais",
    "ellas/ellos/ustedes - ar,an",
    "yo - er,o",
    "tu - er,es",
    "el/ella/usted - er,e",
    "nosotros/nosotras - er,emos",
    "vosotros/vosotras - er,eis",
    "ellas/ellos/ustedes - er,en",
    "yo - ir,o",
    "tu - ir,es",
    "el/ella/usted - ir,e",
    "nosotros/nosotras - ir,imos",
    "vosotros/vosotras - ir,is",
    "ellas/ellos/ustedes - ir,en",
]

const konjugasipast = [
    "yo - ar - preterite,e",
    "tu - ar - preterite,aste",
    "el/ella/usted - ar - preterite,o",
    "nosotros/nosotras - ar - preterite,amos",
    "vosotros/vosotras - ar - preterite,asteis",
    "ellas/ellos/ustedes - ar - preterite,aron",
    "yo - er/ir - preterite,i",
    "tu - er/ir - preterite,iste",
    "el/ella/usted - er/ir - preterite,io",
    "nosotros/nosotras - er/ir - preterite,imos",
    "vosotros/vosotras - er/ir - preterite,isteis",
    "ellas/ellos/ustedes - er/ir - preterite,ieron",
]