const question = [
    "eat,comer",
    "drink,beber",
    "study,estudiar",
    "read,leer",
    "write,escribir",
    "because,poque",
    "you all plural,usted",
    "he,el",
    "she,ella",
    "walk,caminar",
    "see,ver",
    "think,pensar",
    "feel,sentir",
    "watch,mirar",
    "work,trabajar",
    "ask,preguntar",
    "remember,recordar",
    "allow/permit,permitir",
    "languange,idioma",
    "however,sin embargo",
    "yes,si",
    "people,gente",
    "learn,aprender",
    "to,a",
    "before,antes",
    "today,hoy",
    "yesterday,ayer",
    "tommorow,manana",
    "good morning,buenos dias",
    "good afternoon,buenas tardes",
    "good night,buenas noches",
    "after,despues"
];
